// Icons an admin can pick for a main-menu section or a dropdown link.
// Client-safe data only; the matching lucide components are in
// components/site/menu-icon.tsx.
export const MENU_ICONS = [
  { key: "code", label: "Code" },
  { key: "smartphone", label: "Mobile" },
  { key: "layoutDashboard", label: "Dashboard" },
  { key: "cloud", label: "Cloud" },
  { key: "megaphone", label: "Megaphone" },
  { key: "shieldCheck", label: "Shield" },
  { key: "blocks", label: "Blocks" },
  { key: "palette", label: "Palette" },
  { key: "layers", label: "Layers" },
  { key: "briefcase", label: "Briefcase" },
  { key: "building2", label: "Building" },
  { key: "newspaper", label: "Newspaper" },
  { key: "bookOpen", label: "Book" },
  { key: "fileBarChart", label: "Report" },
  { key: "package", label: "Package" },
  { key: "factory", label: "Factory" },
  { key: "cpu", label: "Chip" },
  { key: "users", label: "People" },
  { key: "usersRound", label: "Team" },
  { key: "workflow", label: "Workflow" },
  { key: "handshake", label: "Handshake" },
  { key: "heartHandshake", label: "Heart & hands" },
  { key: "graduationCap", label: "Graduation" },
  { key: "boxes", label: "Boxes" },
  { key: "shoppingBag", label: "Shopping" },
  { key: "calendarCheck", label: "Calendar" },
  { key: "landmark", label: "Bank" },
  { key: "heartPulse", label: "Health" },
  { key: "truck", label: "Truck" },
  { key: "utensils", label: "Food" },
  { key: "banknote", label: "Money" },
  { key: "mapPin", label: "Location" },
  { key: "globe", label: "Globe" },
  { key: "star", label: "Star" },
  { key: "sparkles", label: "Sparkles" },
  { key: "lifeBuoy", label: "Support" },
  { key: "helpCircle", label: "Help" },
  { key: "trophy", label: "Trophy" },
  { key: "wrench", label: "Wrench" },
  { key: "headset", label: "Headset" },
  { key: "mail", label: "Mail" },
  { key: "phone", label: "Phone" },
  { key: "info", label: "Info" },
  { key: "home", label: "Home" },
] as const;

export type MenuIconKey = (typeof MENU_ICONS)[number]["key"];
export const isMenuIcon = (k: unknown): k is MenuIconKey => MENU_ICONS.some((i) => i.key === k);
