// ============================================================
// UKVALLEY TECHNOLOGIES — /solutions/[slug] content
// One entry per solution page. Edit values here to update.
// ============================================================

export type Solution = {
  slug: string;
  name: string;
  category: string;
  icon: string; // lucide icon key, mapped in the page template
  tagline: string;
  description: string; // used in the hero + meta description
  longDescription: string[];
  metrics: { value: string; label: string }[];
  features: { title: string; desc: string }[];
  modules: string[];
  workflow: { title: string; desc: string }[];
  integrations: string[];
  faqs: { q: string; a: string }[];
  bestFor: string[];
  relatedServices: string[]; // /services slugs
  relatedIndustries: string[]; // /industries slugs
  /** Where the client's team gets its time back — before vs after, per task. */
  timeSavings: { task: string; before: string; after: string }[];
  /** The situations clients arrive with. */
  painPoints: { title: string; desc: string }[];
  /** At-a-glance facts: timeline, team, investment, first demo, support. */
  quickFacts: { label: string; value: string; sub?: string }[];
  /** Measurable outcomes after go-live. */
  outcomes: string[];
  /** What we need from the client to start well. */
  youProvide: string[];
};

export const solutions: Solution[] = [
  {
    slug: "crm",
    name: "CRM Systems",
    category: "Sales & customer management",
    icon: "users",
    tagline: "A CRM that mirrors how your sales team actually sells",
    description:
      "Custom CRM systems built around your real pipeline — lead capture, follow-up cadences, quotations and reporting in one accountable system your team will actually use.",
    longDescription: [
      "Most CRM projects fail for one reason: the tool forces the team into a workflow that some vendor imagined. Leads get re-typed into WhatsApp, quotes live in Excel, and the CRM becomes an expensive contact list. We build the opposite — a CRM mapped to your actual sales process, from first enquiry to invoice.",
      "Every build starts with us shadowing your team for a week. We map how leads arrive (website, WhatsApp, walk-ins, dealers), how follow-ups actually happen, where quotations get stuck and what your managers want to see on Monday morning. Then we ship a thin-slice prototype in week three — real pipeline, real leads, real screens.",
      "The result is one system where nothing falls through: automated follow-up reminders, role-based dashboards, quotation and proforma generation, WhatsApp and email capture, and a full audit trail of who changed what. Managers coach from real data instead of chasing the team for updates.",
      "Look at what the current setup costs before pricing a new one. A lead that arrives on WhatsApp and is never logged is a marketing rupee spent for nothing. A quotation that takes forty-five minutes to type is a rep not selling for forty-five minutes. A follow-up that lives in someone's memory is missed roughly four times in ten — which, on a hundred enquiries a month, is forty conversations that never happened. And when a rep resigns, the pipeline in their phone resigns with them. The spreadsheet is not free; it is simply invoiced in lost deals.",
      "The real test isn't the demo, it's the Monday after go-live: one screen showing every lead, owner and next action; a website enquiry reaching a rep's queue within a minute, source tagged; a quotation out in five minutes; and a resigning rep's pipeline staying behind intact. We scope and demo against exactly those four checks.",
    ],
    metrics: [
      { value: "Zero", label: "Leads dropped" },
      { value: "2.1×", label: "More follow-ups completed" },
      { value: "3 wks", label: "To working prototype" },
    ],
    features: [
      { title: "Lead capture from everywhere", desc: "Website forms, WhatsApp, phone calls, walk-ins and marketplaces — every lead lands in one pipeline with its source tagged." },
      { title: "Pipelines that match reality", desc: "Stages modelled on your sales process, not a generic funnel — with mandatory next-actions so no lead ages silently." },
      { title: "Quotations & proforma", desc: "Generate branded quotations from the deal record, convert to proforma and track approvals without leaving the CRM." },
      { title: "Follow-up automation", desc: "Scheduled reminders, escalation when a follow-up is missed, and daily digest to each rep's phone." },
      { title: "Role-based dashboards", desc: "Reps see their pipeline; managers see conversion, source ROI and team performance — one source of truth." },
      { title: "Full audit trail", desc: "Every edit, note and status change is logged with user and timestamp — accountability by design." },
    ],
    modules: ["Lead & enquiry management", "Deal pipeline & forecasting", "Quotation generator", "Follow-up cadences", "Customer 360° timeline", "Task & meeting tracker", "Reports & exports", "Mobile rep app"],
    workflow: [
      { title: "Shadow your sales floor", desc: "We sit with your team and map the real process — lead sources, stages, objections and hand-offs." },
      { title: "Prototype in week three", desc: "A working pipeline with your real leads loaded — clickable, not a wireframe." },
      { title: "Sprint to full rollout", desc: "Two-week sprints with weekly demos; quotation engine, dashboards and integrations layer in." },
      { title: "Migrate & train", desc: "Spreadsheet and WhatsApp history cleaned, migrated and reconciled — with floor-side training." },
    ],
    integrations: ["Tally", "WhatsApp Business", "Email (SMTP/Gmail)", "SMS gateways", "Google Sheets", "Payment links"],
    faqs: [
      { q: "Can you customise it to our exact sales stages?", a: "That's the entire point — the pipeline, stages, fields and rules are modelled on your process, discovered in the scoping week. Nothing is locked to a vendor's template." },
      { q: "Can it replace our spreadsheets entirely?", a: "Yes. We audit every spreadsheet in use, map its data into the CRM schema, and reconcile the migration before go-live so nothing is lost or duplicated." },
      { q: "Does it work on mobile for field reps?", a: "Yes — a responsive web app by default, or a dedicated Flutter app with offline capture when reps work in low-connectivity areas." },
      { q: "How is this different from off-the-shelf CRM?", a: "Off-the-shelf tools bend your process to their shape; we build software that matches yours. You also own the code outright, so there are no per-seat licence creep or vendor lock-in." },
    ],
    bestFor: ["Real estate & brokerages", "Industrial sales teams", "Insurance & financial advisors", "Distributors & dealers", "Automobile dealerships"],
    relatedServices: ["custom-software", "web-development", "mobile-app-development"],
    relatedIndustries: ["real-estate", "professional-services", "retail-ecommerce"],
    painPoints: [
      { title: "Leads live in five inboxes", desc: "Portal, website, WhatsApp, walk-ins and brokers each land somewhere different; nobody has the full list." },
      { title: "Follow-ups depend on memory", desc: "No owner, no due date, no escalation — the second call is the one that never happens." },
      { title: "Quotations take an afternoon", desc: "Typed in Word from last quarter's price list, then emailed and forgotten." },
      { title: "Managers cannot see the pipeline", desc: "Monday reviews are built from three files and a phone round, and are out of date by Tuesday." },
    ],
    quickFacts: [
      { label: "Typical timeline", value: "6–10 wks", sub: "Pipeline live by week 3" },
      { label: "Team on it", value: "3–4", sub: "Architect, full-stack, mobile, QA" },
      { label: "Starting investment", value: "₹6 lakh", sub: "Single-team CRM with Tally sync" },
      { label: "First working demo", value: "Week 3", sub: "Your real leads loaded" },
      { label: "After launch", value: "1 quarter", sub: "Support and training included" },
    ],
    outcomes: [
      "Every lead from every source in one pipeline with an owner and a due action",
      "Missed follow-ups escalated the same day instead of discovered at month-end",
      "Quotations and proformas generated from the deal record in minutes",
      "Source-wise conversion and rep performance visible on a live dashboard",
      "A complete history of every customer interaction that stays when a rep leaves",
    ],
    youProvide: [
      "A week of access to shadow your sales team and their current sheets",
      "Your lead sources: portal logins, website forms, WhatsApp numbers",
      "Your quotation formats, price lists and approval rules",
      "One sales owner for the weekly demo and the migration sign-off",
    ],
    timeSavings: [
      { task: "Logging a new lead", before: "5 min re-typed into a sheet", after: "Auto-captured with source tag" },
      { task: "Weekly pipeline review", before: "3 hrs assembling three files", after: "Live dashboard, 10 min" },
      { task: "Preparing a quotation", before: "45 min per quote in Word", after: "4 min from the deal record" },
      { task: "Follow-up tracking", before: "From memory, ~40% missed", after: "Scheduled, escalated if missed" },
    ],
  },
  {
    slug: "erp",
    name: "ERP Systems",
    category: "Operations & back office",
    icon: "layoutDashboard",
    tagline: "One system for inventory, orders, accounting and people",
    description:
      "Custom ERP built around your operations — inventory, procurement, orders, GST-compliant accounting and role-based access in one auditable platform.",
    longDescription: [
      "An ERP is not software; it's your operating discipline made digital. Generic ERPs force SMEs into processes built for other industries, and the result is the classic pattern: the ERP runs the accounts while the real business runs on WhatsApp and spreadsheets beside it.",
      "We build ERPs the other way around. In the scoping week we trace one order through your business end to end — enquiry, quotation, purchase, stock, dispatch, invoice, payment — and model the system on that real flow, including the exceptions your team actually handles daily.",
      "The finished system gives you live stock across godowns, purchase automation against reorder thresholds, GST-ready invoicing, production or service job cards, and management dashboards where every number traces back to a transaction. Your CA and your floor supervisor finally read the same data.",
      "The cost of running operations beside the accounts rather than inside them shows up everywhere except the P&L. Stock that exists in the register but not on the shelf is discovered at the annual count. A purchase order raised late because nobody saw the reorder point becomes an emergency buy at a premium. An invoice re-keyed into Tally is a chance for a GST mismatch and a notice. And month-end, assembled from a dozen spreadsheets, arrives three days late — which means the owner makes this month's decisions on last month's numbers.",
      "An ERP earns its place when the floor and the office stop arguing about the numbers — ask the storekeeper, the purchase manager and the accountant what's in stock, and get one answer. We go live on inventory and invoicing first, then run a full parallel month against Tally before anyone switches over.",
    ],
    metrics: [
      { value: "25%", label: "Lower inventory cost" },
      { value: "1 truth", label: "Single source of data" },
      { value: "100%", label: "GST-ready records" },
    ],
    features: [
      { title: "Live inventory across godowns", desc: "Real-time stock by location, batch and SKU — with reorder alerts before you run out, not after." },
      { title: "Procurement automation", desc: "Purchase indents, vendor comparison, approval chains and GRN flows mapped to your controls." },
      { title: "GST-compliant invoicing", desc: "Sales and purchase invoices with HSN, e-invoice and e-way bill readiness built in." },
      { title: "Order-to-cash tracking", desc: "Every order visible from indent to dispatch to payment — with ageing and outstanding reports." },
      { title: "Role-based access", desc: "Floor staff, managers, accountants and owners each see exactly what they should — nothing more." },
      { title: "Audit trail on everything", desc: "Stock moves, price changes and approvals are logged — discrepancies become traceable events." },
    ],
    modules: ["Inventory & godowns", "Purchase & vendors", "Sales & invoicing", "Accounting & GST", "Production / job cards", "HR & attendance", "Reports & dashboards", "Approval workflows"],
    workflow: [
      { title: "Trace one real order", desc: "We document your order-to-cash journey exactly as it happens, exceptions included." },
      { title: "Data model sign-off", desc: "Items, tax rules, approval chains and godown structure agreed in writing before code." },
      { title: "Thin slice in production", desc: "Inventory plus invoicing live on real data by week three — value starts flowing early." },
      { title: "Migrate & parallel-run", desc: "Opening balances and master data migrated, with a parallel-run window against Tally." },
    ],
    integrations: ["Tally", "e-Invoice / e-Way Bill", "Payment gateways", "Barcode scanners", "Email & SMS", "Excel import/export"],
    faqs: [
      { q: "Can it replace Tally, or work with it?", a: "Both. Many clients keep Tally for statutory books while our ERP runs operations and syncs vouchers to it. Others migrate off entirely. We recommend based on your CA's workflow." },
      { q: "How long does an SME ERP take?", a: "A focused scope — inventory, invoicing, purchase and reports — typically reaches production in 8–12 weeks. Broader scopes with production planning or HR take longer, staged in sprints." },
      { q: "What about our existing data?", a: "We audit and clean master data (items, vendors, customers), map opening balances, and reconcile trial runs before go-live. Messy Excel data is normal — we handle it." },
      { q: "Who trains our staff?", a: "We train role by role on your real data, leave recorded walkthroughs, and stay on-call through the first month of live operations." },
    ],
    bestFor: ["Manufacturing & job work", "Trading & distribution", "Multi-godown retailers", "Service companies with billing", "Pharma & FMCG distributors"],
    relatedServices: ["custom-software", "cloud-devops", "web-development"],
    relatedIndustries: ["manufacturing", "retail-ecommerce", "logistics"],
    painPoints: [
      { title: "Three stock numbers, none of them right", desc: "The register, the godown and the website disagree, and the truth is discovered at the annual count." },
      { title: "Purchases are emergencies", desc: "Reorder points live in someone's head, so stock-outs become premium-price rush buys." },
      { title: "Tally is the only system that works", desc: "Operations run on WhatsApp and sheets, then get re-keyed into Tally with mismatches and notices." },
      { title: "Month-end MIS is three days late", desc: "Consolidated from a dozen files, by which time the decisions it was meant to inform are already made." },
    ],
    quickFacts: [
      { label: "Typical timeline", value: "8–12 wks", sub: "Inventory + invoicing live by week 3" },
      { label: "Team on it", value: "4–6", sub: "Architect, full-stack, QA, data migration" },
      { label: "Starting investment", value: "₹10 lakh", sub: "Inventory, purchase, sales, GST" },
      { label: "First working demo", value: "Week 3", sub: "Live stock on your master data" },
      { label: "Cutover", value: "Parallel run", sub: "Reconciled against Tally first" },
    ],
    outcomes: [
      "One stock ledger across godowns, counters and channels, updated with every transaction",
      "Purchase suggestions generated from real sell-through and reorder thresholds",
      "GST-compliant invoices with e-invoice and e-way bill readiness, synced to Tally",
      "Month-end MIS available the same day, with every number traceable to a transaction",
      "Role-based access so the floor, the manager and the accountant see exactly their part",
    ],
    youProvide: [
      "Item, vendor and customer master data, however messy it is today",
      "One real order traced end to end with us in the scoping week",
      "Your CA's preference: keep Tally for statutory books, or migrate off it",
      "A department owner for each module and the parallel-run sign-off",
    ],
    timeSavings: [
      { task: "Stock count per godown", before: "2 days a month by hand", after: "Live, reconciled daily" },
      { task: "Raising a purchase order", before: "1 hr per PO across emails", after: "10 min from a reorder alert" },
      { task: "GST invoicing", before: "20 min per invoice, re-entered in Tally", after: "One click, synced to Tally" },
      { task: "Month-end MIS", before: "3 days of spreadsheet consolidation", after: "Same-day dashboard" },
    ],
  },
  {
    slug: "hrms",
    name: "HRMS & Payroll",
    category: "People operations",
    icon: "briefcase",
    tagline: "Attendance to payslip, without the month-end scramble",
    description:
      "HRMS and payroll built for Indian labour and tax rules — attendance, leave, shifts, payroll, compliance and employee self-service in one system.",
    longDescription: [
      "Indian payroll is genuinely hard: PF, ESI, professional tax, TDS, gratuity, bonus act, state-wise rules — and every HR software demos beautifully until the first month-end. We build HRMS around your actual pay structure and compliance calendar, then automate the scramble away.",
      "Attendance comes first because payroll is only as good as its inputs. We integrate biometric devices, mobile check-in with geo-fencing for field staff, shift rosters and overtime rules — so the payroll run starts from clean, reconciled data instead of Excel consolidation.",
      "Employees get a self-service app: payslips, leave balances, requests, reimbursements and documents. HR gets workflows instead of paperwork. Finance gets compliant journals and statutory registers. Month-end becomes a review, not a fire drill.",
      "Manual payroll is expensive in ways that never appear as a line item. Two days of HR time every month spent consolidating attendance from devices and chat groups. Overtime rules applied from memory, producing disputes that cost a supervisor an afternoon each. Professional tax slabs missed for one state and corrected with a penalty. Statutory challans prepared at the last minute and re-typed from screenshots. And thirty walk-ups a week for payslips and leave balances — each a five-minute interruption for someone whose job was supposed to be hiring and retention.",
      "The proof of an HRMS is the month-end nobody notices: attendance already reconciled, payroll run in a morning from HR's own rules, and challans generated ready to file — not re-typed from screenshots. We verify this with one full parallel payroll run, reconciled line by line, before cutover.",
    ],
    metrics: [
      { value: "70%", label: "Less HR paperwork" },
      { value: "1 day", label: "Payroll run time" },
      { value: "100%", label: "Statutory records" },
    ],
    features: [
      { title: "Biometric & mobile attendance", desc: "Device integrations, geo-fenced mobile check-in and shift rosters reconciled automatically." },
      { title: "Leave & shift management", desc: "Policy-driven accruals, comp-offs, week-off rules and team calendars in one place." },
      { title: "Indian payroll engine", desc: "PF, ESI, PT, TDS, gratuity and bonus computed from your salary structures, with revision history." },
      { title: "Statutory compliance", desc: "Challans, registers and returns-ready reports — audit-ready records, not screenshots." },
      { title: "Employee self-service", desc: "Payslips, leave requests, reimbursements and documents on each employee's phone." },
      { title: "Full & final settlement", desc: "Exit workflows with leave encashment, notice recovery and FnF statements generated automatically." },
    ],
    modules: ["Attendance & shifts", "Leave policies", "Payroll & TDS", "Reimbursements", "Employee portal", "Onboarding & exits", "Appraisals", "Statutory reports"],
    workflow: [
      { title: "Map pay structures", desc: "Salary templates, statutory settings and shift rules documented and signed off." },
      { title: "Attendance pilot", desc: "Biometric/mobile capture live for one unit first; reconciliation verified against existing records." },
      { title: "Parallel payroll run", desc: "First payroll computed in both systems and compared line by line before cutover." },
      { title: "Go live & self-serve", desc: "Employee app rollout with training; HR moves from data entry to exceptions." },
    ],
    integrations: ["Biometric devices", "Tally & accounting", "Bank salary files", "ESIC / EPFO portals", "Email & SMS", "Excel import"],
    faqs: [
      { q: "Does it handle our state's professional tax?", a: "Yes — PT slabs are configured per state of employment, along with PF, ESI, LWF and TDS settings, all editable when rules change." },
      { q: "Can field staff mark attendance by phone?", a: "Yes — mobile check-in with geo-fencing and optional selfie verification, with offline capture that syncs when connectivity returns." },
      { q: "What if we already use biometric devices?", a: "We integrate with the devices you have. Most major brands expose logs we can pull directly — no need to buy new hardware." },
      { q: "Is the payroll verified before we trust it?", a: "We run one payroll in parallel with your existing process and reconcile every line item before switching over. Nothing goes live unverified." },
    ],
    bestFor: ["Factories & shifts", "Multi-branch SMEs", "Staffing & facility firms", "Growing startups (50–500 staff)", "Healthcare & diagnostic chains"],
    relatedServices: ["custom-software", "mobile-app-development", "web-development"],
    relatedIndustries: ["manufacturing", "professional-services", "logistics"],
    painPoints: [
      { title: "Attendance arrives from everywhere", desc: "Biometric logs, a WhatsApp leave group and a paper shift roster consolidated by hand every month." },
      { title: "Payroll disputes every cycle", desc: "Overtime and shift allowances applied from memory, so the same argument repeats each month." },
      { title: "Statutory filings at the last minute", desc: "PF, ESI and PT challans prepared from screenshots, with corrections after the deadline." },
      { title: "HR is a help desk", desc: "Dozens of walk-ups a week for payslips and leave balances that employees could answer themselves." },
    ],
    quickFacts: [
      { label: "Typical timeline", value: "8–14 wks", sub: "Attendance pilot by week 3" },
      { label: "Team on it", value: "3–5", sub: "Architect, backend, mobile, QA" },
      { label: "Starting investment", value: "₹8 lakh", sub: "Single entity, up to 500 staff" },
      { label: "First working demo", value: "Week 3", sub: "Live attendance from your devices" },
      { label: "Cutover", value: "Parallel payroll", sub: "Reconciled line by line first" },
    ],
    outcomes: [
      "Attendance from every device and mobile check-in in one stream, exceptions flagged automatically",
      "Payroll computed from configured shift, overtime and statutory rules — not from memory",
      "PF, ESI, PT and TDS outputs generated ready to file, every month",
      "Employees viewing payslips, balances and requests on their own phones",
      "Month-end payroll closed in one day, verified against a parallel run before go-live",
    ],
    youProvide: [
      "Your salary structures, shift rules and leave policies as they are practised",
      "Access to the biometric devices and any existing attendance exports",
      "Statutory registrations and one past payroll for the parallel run",
      "An HR owner for policy sign-off and the employee-app rollout",
    ],
    timeSavings: [
      { task: "Attendance consolidation", before: "2 days every month", after: "Automatic, exceptions only" },
      { task: "Payroll run", before: "1–2 days with corrections", after: "1 day, verified line by line" },
      { task: "PF / ESI / PT challans", before: "Half a day, re-typed", after: "Generated ready to file" },
      { task: "Payslip & leave queries", before: "30+ HR walk-ups a week", after: "Self-service on the phone" },
    ],
  },
  {
    slug: "lms",
    name: "Learning Management (LMS)",
    category: "Education & training",
    icon: "graduationCap",
    tagline: "Courses that work on the devices students actually own",
    description:
      "Learning management systems built for Indian learners — video classes on low bandwidth, admissions, fees, exams and parent apps in one platform.",
    longDescription: [
      "Most LMS platforms are built for campuses with fibre and laptops. Indian learners are on mid-range Androids and intermittent 4G — so the platforms that succeed here are engineered for low bandwidth, offline playback and tiny storage footprints, not just feature lists.",
      "We build LMS platforms with exactly that discipline: adaptive video streaming, downloadable lessons, WhatsApp-friendly notifications, and interfaces that stay fast on ₹10,000 phones. Coaching institutes, schools and corporate training teams use the same core — courses, batches, attendance, assessments.",
      "Around the learning core sit the operations that actually run an institute: enquiry-to-admission pipelines, instalment-based fee collection with reminders, exam and result workflows, and parent-facing apps that show attendance and progress without calling the office.",
      "An institute without a working learning platform pays for it in attention and admin. Students on patchy 4G abandon a video that buffers, and a course they abandon is a fee they do not renew. Fees collected across cash, UPI and bank are reconciled by hand each term, and defaulters are discovered late. Report cards are compiled per class in Excel and re-typed into the board format. And parents, unable to see attendance or homework without calling, either call constantly or disengage entirely — both of which cost the front desk and the child.",
      "The measure of a learning platform is whether it's opened voluntarily — lessons that don't buffer on a commute, homework and attendance in a notification instead of a phone call, a class post from a teacher's phone in under a minute. We build that daily-use core first, then layer in fees and admissions.",
    ],
    metrics: [
      { value: "3×", label: "More course completions" },
      { value: "Low", label: "Bandwidth video" },
      { value: "24/7", label: "Student access" },
    ],
    features: [
      { title: "Low-bandwidth video", desc: "Adaptive streaming and downloadable lessons that play reliably on mid-range Android devices." },
      { title: "Batches & live classes", desc: "Batch timetables, Zoom/Meet integration and attendance that feeds progress reports." },
      { title: "Tests & auto-grading", desc: "MCQ, subjective and OMR-style assessments with instant scoring and analytics per topic." },
      { title: "Fee workflows", desc: "Instalment plans, due-date reminders, payment links and defaulter tracking for the office." },
      { title: "Admissions pipeline", desc: "Enquiry, counselling, documents and enrolment tracked like a sales funnel — because it is one." },
      { title: "Parent & student apps", desc: "Attendance, homework, results and notices on the family's phone — reducing front-desk calls." },
    ],
    modules: ["Course & lesson library", "Batches & timetables", "Live class integration", "Assessments & results", "Fee & instalment tracking", "Admissions CRM", "Parent/student app", "Certificate generation"],
    workflow: [
      { title: "Model your institute", desc: "Courses, batches, fee structures and staff roles mapped in the scoping week." },
      { title: "Core first", desc: "Course library, batches and attendance live first — the daily-use path." },
      { title: "Fees & admissions", desc: "Office workflows layered in with payment gateway and reminder automation." },
      { title: "Apps & rollout", desc: "Student/parent apps launched with a batch-wise onboarding plan." },
    ],
    integrations: ["Zoom / Google Meet", "Payment gateways", "WhatsApp notifications", "SMS gateways", "YouTube/Vimeo unlisted", "Excel import"],
    faqs: [
      { q: "Will video work for students on slow connections?", a: "Yes — adaptive bitrate streaming, downloadable lessons and 360p-first defaults. We test on real mid-range Android devices, not office Wi-Fi." },
      { q: "Can it run exams securely?", a: "Objective tests are auto-graded with randomized question pools and time limits; subjective answers flow through a grading queue. For high-stakes exams we add question-paper workflows and audit logs." },
      { q: "Does it handle instalment-based fees?", a: "Yes — plans with due dates, automatic reminders, payment links and defaulter lists are a core module, not an afterthought." },
      { q: "Can teachers upload their own content?", a: "Yes — role-based upload with review workflows so administrators control what goes live to students." },
    ],
    bestFor: ["Coaching institutes", "Schools & colleges", "Corporate training teams", "Online course creators", "Edtech startups"],
    relatedServices: ["custom-software", "mobile-app-development", "web-development"],
    relatedIndustries: ["education-edtech", "professional-services", "healthcare"],
    painPoints: [
      { title: "Video that buffers on real connections", desc: "Platforms built for campus fibre stall on the 4G and mid-range phones students actually use." },
      { title: "Fees reconciled by hand", desc: "Cash, UPI and bank receipts matched against a spreadsheet every term; defaulters found late." },
      { title: "Report cards take days", desc: "Marks compiled per class in Excel and re-typed into the board's format." },
      { title: "Parents either call constantly or disengage", desc: "No way to see attendance or homework without phoning the office, so notices go unread." },
    ],
    quickFacts: [
      { label: "Typical timeline", value: "10–16 wks", sub: "Course core live by week 3" },
      { label: "Team on it", value: "4–6", sub: "Architect, backend, mobile, QA" },
      { label: "Starting investment", value: "₹8 lakh", sub: "Single institute or campus" },
      { label: "First working demo", value: "Week 3", sub: "Courses and batches on real devices" },
      { label: "Rollout", value: "Batch-wise", sub: "Teachers trained on their own classes" },
    ],
    outcomes: [
      "Video and lessons that play on mid-range Android over 4G, with downloads that resume",
      "Fee schedules, reminders and payment links with automatic bank reconciliation",
      "Board-format report cards generated from marks entry in minutes",
      "A parent app opened daily for homework, attendance and notices",
      "One data model across every campus with per-campus branding and reporting",
    ],
    youProvide: [
      "Course structure, batches, fee plans and the academic calendar",
      "A few teachers and parents with their own devices for testing",
      "Your existing fee records and student master data for migration",
      "An academic owner and an accounts owner for sign-offs",
    ],
    timeSavings: [
      { task: "Fee reconciliation", before: "1 day per term per campus", after: "Automatic against the bank statement" },
      { task: "Report cards", before: "2 days per class per term", after: "Generated in minutes" },
      { task: "Parent communication", before: "Muted WhatsApp groups", after: "Push + WhatsApp with read receipts" },
      { task: "Attendance & homework", before: "Registers re-keyed weekly", after: "Captured live, offline-first" },
    ],
  },
  {
    slug: "ecommerce",
    name: "E-commerce Platforms",
    category: "Selling online",
    icon: "shoppingBag",
    tagline: "Storefronts engineered for Indian payments and logistics",
    description:
      "Custom e-commerce platforms — storefront, cart, COD and prepaid flows, GST invoicing, shipping integrations and an admin built for your catalogue.",
    longDescription: [
      "Templated stores break at Indian realities: RTO-heavy COD, partial cancellations, GST variations, regional shipping surcharges and a catalogue that changes with the season. We build storefronts where those are first-class features, not plugins you discover missing at go-live.",
      "The storefront itself is engineered for conversion: server-rendered for SEO and speed on mid-range phones, one-page checkout with UPI-first payment ordering, and abandonment recovery via WhatsApp. Product pages ship with schema markup so Google Shopping and rich results work from day one.",
      "Behind it, the admin is built for your operations — bulk catalogue updates, order-wise COD confirmation flows, shipping integrations (Delhivery, Shiprocket, Bluedart), label printing, GST invoices and RTO analytics. You see margin per order, not just revenue.",
      "A templated store leaks margin at exactly the points Indian retail is hardest. Every COD order that returns to origin costs two-way shipping, packaging and a week of working capital. Every product page that loads slowly on a mid-range phone loses the shopper the ad just paid for. Every shipping label generated across three courier portals is five minutes a store cannot spare during a sale. And without pincode, product and customer-level return data, the only lever left is to switch COD off — which trades the biggest revenue stream for a small reduction in risk.",
      "A storefront built for Indian operations lets you ask sharper questions — net revenue per order after shipping and returns, by pincode and product — instead of just gross revenue. We build for speed on real phones, a UPI-first checkout, and an admin around your operations team's real day, so the platform recovers margin, not just traffic.",
    ],
    metrics: [
      { value: "<2.5s", label: "LCP on 4G" },
      { value: "UPI", label: "First in checkout" },
      { value: "100%", label: "GST invoices" },
    ],
    features: [
      { title: "Speed on mid-range phones", desc: "Server-rendered pages, tuned images and lazy hydration — Core Web Vitals in the green." },
      { title: "COD done properly", desc: "Order confirmation calls/WhatsApp, COD fee rules by pincode, and RTO-risk scoring on repeat refusers." },
      { title: "UPI-first checkout", desc: "UPI, cards, wallets and net-banking via Razorpay/Cashfree, with one-page checkout and saved carts." },
      { title: "Shipping integrations", desc: "Delhivery, Shiprocket, Bluedart and more — rates, labels, tracking and NDR workflows." },
      { title: "GST-ready invoicing", desc: "HSN-wise invoices, credit notes for returns and export-ready accounting reports." },
      { title: "Operations admin", desc: "Bulk catalogue tools, order pipelines, partial fulfilment and margin-per-order analytics." },
    ],
    modules: ["Storefront & PDP", "Cart & checkout", "Payments & COD", "Order management", "Shipping & tracking", "Catalogue admin", "GST invoicing", "Discounts & campaigns"],
    workflow: [
      { title: "Catalogue & rules", desc: "Categories, variants, tax slabs, shipping zones and COD rules documented up front." },
      { title: "Storefront first", desc: "Search-to-checkout live as a thin slice, tested on real devices and real pin codes." },
      { title: "Ops layer", desc: "Shipping, invoicing, returns and admin tooling wired in before marketing spend." },
      { title: "Launch & iterate", desc: "Go live with analytics on conversion, RTO and margin — then tune weekly." },
    ],
    integrations: ["Razorpay / Cashfree", "Delhivery / Shiprocket", "WhatsApp Business", "Tally", "Meta & Google feeds", "SMS gateways"],
    faqs: [
      { q: "Shopify or custom — which should we pick?", a: "Shopify is right for standard catalogues that fit its model. Custom wins when your operations are unusual — complex variants, B2B pricing, COD rules, or margin-critical analytics. We give a written recommendation either way." },
      { q: "Can you reduce our COD RTO?", a: "Yes — confirmation workflows, pincode risk rules, repeat-refuser flags and prepaid incentives typically cut RTO meaningfully. The exact gain depends on your category." },
      { q: "Do you migrate from an existing platform?", a: "Yes — products, customers, orders and SEO redirects are migrated in a planned cutover so rankings and history carry over." },
      { q: "Who owns the platform?", a: "You do — source code, data and credentials from day one. No per-order commissions to us, no platform lock-in." },
    ],
    bestFor: ["D2C brands", "Manufacturers selling direct", "Multi-brand retailers", "B2B ordering portals", "Kirana & supermarket chains going online"],
    relatedServices: ["web-development", "digital-marketing", "graphic-design"],
    relatedIndustries: ["retail-ecommerce", "manufacturing", "logistics"],
    painPoints: [
      { title: "COD returns eat the margin", desc: "A third of cash-on-delivery orders come back, and the only tool on offer is switching COD off." },
      { title: "Slow pages on real phones", desc: "The ad delivers the shopper; the four-second product page sends them away." },
      { title: "Fulfilment across three portals", desc: "Labels, tracking and returns handled in separate courier dashboards, order by order." },
      { title: "Revenue known, margin unknown", desc: "Shipping, returns and discounts are never attributed per order, so profitable products are a guess." },
    ],
    quickFacts: [
      { label: "Typical timeline", value: "8–12 wks", sub: "Search-to-checkout live by week 3" },
      { label: "Team on it", value: "3–5", sub: "Architect, front-end, backend, QA" },
      { label: "Starting investment", value: "₹8 lakh", sub: "Storefront, checkout, ops admin" },
      { label: "First working demo", value: "Week 3", sub: "Real catalogue, real pincodes" },
      { label: "Performance", value: "<2.5s", sub: "LCP on 4G, every page" },
    ],
    outcomes: [
      "Product pages that load in under 2.5 seconds on a mid-range Android",
      "COD orders confirmed on WhatsApp before dispatch, with pincode-level risk rules",
      "UPI-first checkout with saved addresses and a measurable rise in prepaid share",
      "Labels, tracking and returns handled from one admin across couriers",
      "Margin per order, return rate per pincode and courier SLA on one dashboard",
    ],
    youProvide: [
      "Your catalogue with variants, tax slabs and images",
      "Courier and payment gateway accounts, plus past order and return exports",
      "Shipping zones, COD rules and discount policies you run today",
      "An operations owner for the launch checklist and weekly demo",
    ],
    timeSavings: [
      { task: "COD order confirmation", before: "Manual calls, 3 min each", after: "Automatic WhatsApp confirm" },
      { task: "Shipping labels", before: "5 min per order across portals", after: "Batch print, seconds per order" },
      { task: "Catalogue updates", before: "Product-by-product edits", after: "Bulk upload in minutes" },
      { task: "Returns tracking", before: "Spreadsheet, updated weekly", after: "Live RTO dashboard" },
    ],
  },
  {
    slug: "booking-appointments",
    name: "Booking & Appointments",
    category: "Scheduling & reservations",
    icon: "calendarCheck",
    tagline: "Slots, staff and reminders — zero double bookings",
    description:
      "Appointment and booking systems with real-time availability, staff rosters, payments and automated reminders — for clinics, salons, studios and consultants.",
    longDescription: [
      "A booking system is really three systems: a calendar that can't double-book, a payment flow that reduces no-shows, and a reminder cadence that fills cancellations. Get any one wrong and customers go back to calling — which is exactly what the system was meant to prevent.",
      "We build booking platforms with real-time slot engines: services with durations and buffer rules, staff-specific availability, leave and holiday handling, and concurrency-safe confirmation so two people can never grab the same slot. Over-the-counter and phone bookings live in the same calendar as online ones.",
      "No-shows are a payments-and-reminders problem. We wire in advance deposits or full prepay where appropriate, UPI-first payment links, and multi-touch reminders over WhatsApp and SMS with one-tap reschedule. Clinics typically see no-shows drop by a third in the first quarter.",
      "Phone-and-diary booking costs a service business its most valuable hours twice over. The receptionist spends the morning on reminder calls that go unanswered, then the afternoon apologising for a double booking. A no-show leaves a chair, a court or a consultant idle for a slot that could have been resold — and with no reminder chain, a quarter of bookings never turn up. Unpaid holds block the calendar for customers who were never coming. And the owner, without utilisation data, cannot tell which staff, rooms or hours are actually earning.",
      "A booking system succeeds when customers stop calling and staff stop apologising: a booking page showing only real availability, a payment step that turns a hold into a commitment, and a front desk where walk-ins and online bookings share one calendar. We launch the booking page first, then tune deposits and reminders against your own no-show data.",
    ],
    metrics: [
      { value: "0", label: "Double bookings" },
      { value: "-35%", label: "No-shows typical" },
      { value: "24/7", label: "Self-serve booking" },
    ],
    features: [
      { title: "Real-time slot engine", desc: "Concurrency-safe availability with buffers, staff rules and holiday calendars — no double bookings, ever." },
      { title: "Staff & resource rosters", desc: "Multiple providers, rooms or courts with individual schedules and utilisation reporting." },
      { title: "Advance & full payments", desc: "UPI-first deposits or prepay with automatic refunds and payment-verified booking priority." },
      { title: "WhatsApp & SMS reminders", desc: "Multi-touch cadences with one-tap confirm or reschedule — no-shows become cancellations you can refill." },
      { title: "Walk-in & phone bookings", desc: "Front-desk bookings share the same calendar and customer records as online ones." },
      { title: "Customer history", desc: "Every visit, note and preference on one profile — regulars get recognised, not re-asked." },
    ],
    modules: ["Service & staff setup", "Availability engine", "Online booking page", "Payments & deposits", "Reminder automation", "Front-desk console", "Customer records", "Utilisation reports"],
    workflow: [
      { title: "Model services & staff", desc: "Durations, buffers, rosters and policies mapped from how your front desk actually works." },
      { title: "Booking page first", desc: "Public booking live in weeks, sharing one calendar with your current process." },
      { title: "Payments & reminders", desc: "Deposit rules and reminder cadences tuned against real no-show data." },
      { title: "Cut the phone queue", desc: "Front-desk console and reporting live; walk-ins and online in one system." },
    ],
    integrations: ["WhatsApp Business", "SMS gateways", "Razorpay / Cashfree", "Google Calendar", "Zoom / Meet", "Email"],
    faqs: [
      { q: "Can it handle multiple locations?", a: "Yes — each location keeps its own services, staff and calendar, while owners see utilisation and revenue across all of them." },
      { q: "What about customers who book and don't pay?", a: "Unpaid holds auto-expire after your chosen window, and payment-verified bookings get priority slots — incentives that keep the calendar honest." },
      { q: "Does it work for group classes or events?", a: "Yes — capacity-based sessions with waitlists, package redemptions and per-class rosters." },
      { q: "Can customers reschedule themselves?", a: "Yes — one-tap reschedule from the reminder within your policy windows, which turns no-shows into refilled slots." },
    ],
    bestFor: ["Clinics & diagnostics", "Salons & spas", "Coaches & consultants", "Studios & turf venues", "Dental & eye chains"],
    relatedServices: ["custom-software", "mobile-app-development", "web-development"],
    relatedIndustries: ["healthcare", "travel-hospitality", "professional-services"],
    painPoints: [
      { title: "Reception spends the day on reminders", desc: "Hours of calls that go unanswered, then apologies when two people arrive for one slot." },
      { title: "No-shows leave chairs empty", desc: "A quarter of bookings never turn up, and the slot could not be resold because nobody knew." },
      { title: "Unpaid holds block the calendar", desc: "Bookings with no payment behind them keep genuine customers out." },
      { title: "Utilisation is a guess", desc: "Which staff, rooms and hours earn is unknown until month-end, if then." },
    ],
    quickFacts: [
      { label: "Typical timeline", value: "5–8 wks", sub: "Booking page live by week 3" },
      { label: "Team on it", value: "2–4", sub: "Architect, full-stack, QA" },
      { label: "Starting investment", value: "₹4 lakh", sub: "Single location, online + front desk" },
      { label: "First working demo", value: "Week 3", sub: "Public booking on your calendar" },
      { label: "No-shows", value: "−35%", sub: "Typical in the first quarter" },
    ],
    outcomes: [
      "Zero double bookings from a concurrency-safe slot engine with buffers and rosters",
      "Automated WhatsApp confirmations and reminders with one-tap reschedule",
      "Unpaid holds that expire automatically and payment-verified bookings that get priority",
      "Walk-ins, phone and online bookings in one calendar with one customer record",
      "Utilisation and revenue per staff member, room and hour on a live dashboard",
    ],
    youProvide: [
      "Your services, durations, staff rosters and holiday calendar",
      "A WhatsApp Business number and a payment gateway account (we help set both up)",
      "Your cancellation, deposit and reschedule policies",
      "A front-desk owner to test the console before go-live",
    ],
    timeSavings: [
      { task: "Reminder calls", before: "3–4 hrs a day at reception", after: "Automated WhatsApp cadence" },
      { task: "Double-booking fixes", before: "Weekly apologies and reshuffles", after: "Zero — the slot engine prevents them" },
      { task: "Payment collection", before: "Chased at the counter", after: "Prepaid link, verified before the slot" },
      { task: "Utilisation reporting", before: "Estimated at month-end", after: "Live per staff member and room" },
    ],
  },
  {
    slug: "pos",
    name: "POS Systems",
    category: "Retail & restaurants",
    icon: "shoppingBag",
    tagline: "Offline-first billing that keeps selling when the internet doesn't",
    description:
      "POS systems built for Indian retail and food service — offline-first terminals, GST billing, inventory sync and multi-store dashboards that survive real network conditions.",
    longDescription: [
      "Cloud-first POS systems fail at the worst moment: a billing rush on a downed line, and the counter is dead. We build offline-first terminals — billing, discounts and receipts keep working locally and sync when connectivity returns. The store sells; the system catches up.",
      "Billing is GST-grade from day one: HSN-wise items, tax rules per category, split payments, returns and exchange workflows, and printed or WhatsApp receipts. Barcode scanning, weighing-scale items and quick-keys are tuned for the speed your counter staff actually need at peak hours.",
      "Above the counters sits the part owners care about: live sales across every store, stock movement, shrinkage and day-closing reports — with automated reorder thresholds feeding your purchase process. One dashboard replaces the evening phone round to every branch.",
      "The wrong point-of-sale system costs a retailer most at the busiest moment. A cloud-dependent terminal stops billing when the broadband drops during the evening rush, and the paper bills written in the meantime never make it into stock. Stock counted weekly by hand means shrinkage and stock-outs are discovered days late. Day-close with cash mismatches takes forty-five minutes per store, every night. And head office, assembling sales from emailed spreadsheets, sees each branch's truth three days after the fact — which is three days too late to reorder.",
      "We judge a POS at the counter, at peak, with the cable pulled out — if billing keeps running and stock still syncs when the line returns, it's passed the only test that matters. From there: reorder suggestions from real stock, self-reconciling day-close, and live sales across every outlet. We pilot one store in parallel before any regional rollout.",
    ],
    metrics: [
      { value: "Offline", label: "Billing never stops" },
      { value: "3×", label: "Faster day-close" },
      { value: "Live", label: "Multi-store view" },
    ],
    features: [
      { title: "Offline-first billing", desc: "Sales continue through outages; everything syncs with conflict-safe reconciliation when the line returns." },
      { title: "GST-grade receipts", desc: "HSN, tax slabs, split payments, returns and exchanges — printed or sent on WhatsApp." },
      { title: "Barcode & quick keys", desc: "Scan, weigh and quick-key flows tuned for peak-hour counter speed." },
      { title: "Inventory sync", desc: "Every bill decrements stock in real time once connected, with reorder alerts per store." },
      { title: "Multi-store dashboard", desc: "Live sales, day-close and shrinkage across all outlets — no evening phone rounds." },
      { title: "Staff & shift control", desc: "Cashier logins, shift opening/closing cash counts and discount-permission rules." },
    ],
    modules: ["Billing terminal", "Offline sync engine", "Inventory & barcodes", "GST invoicing", "Returns & exchanges", "Shift & cash management", "Multi-store dashboard", "Purchase suggestions"],
    workflow: [
      { title: "Pilot store", desc: "One counter runs in parallel with your existing system to validate tax rules and speed." },
      { title: "Rollout by region", desc: "Phased multi-store deployment with on-site training per region." },
      { title: "HQ dashboards", desc: "Consolidated reporting and reorder automation turned on after the first weeks of data." },
      { title: "Support & tune", desc: "24-hour SLA support with monthly reviews of shrinkage and slow-mover reports." },
    ],
    integrations: ["Thermal printers", "Barcode scanners", "Weighing scales", "UPI & card machines", "Tally", "WhatsApp receipts"],
    faqs: [
      { q: "What happens when the internet goes down mid-bill?", a: "Billing continues offline exactly as normal — receipts print, stock decrements locally, and everything syncs automatically when connectivity returns. That's the core of our design." },
      { q: "Can it run on existing hardware?", a: "Usually yes — we support standard Windows/Android terminals and common thermal printers and scanners, so most counters need no new hardware." },
      { q: "Does it handle restaurants separately from retail?", a: "Yes — table/KOT flows, modifications and split bills for F&B; barcode and variant flows for retail. Both share the same inventory and reporting core." },
      { q: "How do you prevent billing fraud?", a: "Role-based discount limits, void permissions, shift cash reconciliation and a full audit trail on every bill — discrepancies become named, timed events." },
    ],
    bestFor: ["QSR & restaurants", "Retail chains", "Supermarkets & kirana", "Apparel & footwear stores", "Cafés & bakeries"],
    relatedServices: ["custom-software", "web-development", "mobile-app-development"],
    relatedIndustries: ["retail-ecommerce", "travel-hospitality", "professional-services"],
    painPoints: [
      { title: "Billing stops when the internet does", desc: "A cloud-only POS goes dark in the evening rush; the paper bills never reach the stock ledger." },
      { title: "Stock counted weekly, by hand", desc: "Shrinkage and stock-outs are found days late, after the sale is lost." },
      { title: "Day-close is a nightly argument", desc: "Cash mismatches and void disputes take forty-five minutes per store, every night." },
      { title: "HQ sees branches three days late", desc: "Sales consolidated from emailed sheets arrive after the reorder decision needed them." },
    ],
    quickFacts: [
      { label: "Typical timeline", value: "6–14 wks", sub: "Pilot store by week 3, then regions" },
      { label: "Team on it", value: "3–5", sub: "Architect, full-stack, QA, rollout lead" },
      { label: "Starting investment", value: "₹6 lakh", sub: "Up to 5 stores with HQ dashboard" },
      { label: "First working demo", value: "Week 3", sub: "Parallel billing in one store" },
      { label: "Hardware", value: "Yours", sub: "Standard terminals and printers supported" },
    ],
    outcomes: [
      "Billing that continues through outages and syncs with conflict-safe reconciliation",
      "Stock decremented per bill in real time, with reorder alerts per store",
      "GST-grade receipts with HSN, split payments, returns and WhatsApp delivery",
      "Day-close reconciled automatically, with shift cash counts and void permissions",
      "Live sales, stock and shrinkage across every outlet on one HQ dashboard",
    ],
    youProvide: [
      "Your item master with HSN codes, tax slabs and barcodes",
      "One pilot store and its counter staff for the parallel run",
      "Details of existing terminals, printers and scanners",
      "Your discount, return and cashier permission rules",
    ],
    timeSavings: [
      { task: "Day-close per store", before: "45 min with cash mismatches", after: "15 min, auto-reconciled" },
      { task: "Stock update after billing", before: "Weekly manual count", after: "Real time, per bill" },
      { task: "HQ sales report", before: "200 emailed sheets, 3 days", after: "Live dashboard" },
      { task: "Billing during an outage", before: "Stops; paper bills entered later", after: "Continues offline, syncs later" },
    ],
  },
  {
    slug: "loan-origination",
    name: "Loan Origination",
    category: "FinTech & lending",
    icon: "landmark",
    tagline: "Application to disbursal, audit-ready at every step",
    description:
      "Loan origination systems with KYC, scoring, workflow and disbursal tracking — built for NBFC and lending startups, audit-ready by design.",
    longDescription: [
      "Lending software is compliance software. Every application, decision and disbursal must be traceable — not because an auditor might ask, but because regulators do. We build origination platforms where the audit trail is the architecture, not a feature added before inspection.",
      "The pipeline mirrors how lending teams work: enquiry and document capture, bureau and KYC verification, rule-plus-scorecard based decisions, approval chains with maker-checker controls, agreement generation, and disbursal tracking with repayment schedules feeding collections.",
      "We've shipped this exact system for an NBFC client, so the edge cases are known: co-applicants, deviation approvals, part disbursements, foreclosure math and NPA classification. Your credit policy becomes configuration, not code changes every quarter.",
      "A lending desk on spreadsheets pays for it in speed, risk and inspections. A file that takes nine working days from application to decision is a customer who took the competitor's offer on day four. KYC documents in WhatsApp threads are a privacy incident waiting for a complaint. A decision taken from memory of the policy is a deviation nobody approved on record. And when the regulator asks for the trail on a sample of files, the answer is reconstructed by hand over weeks — during which the credit team is not lending.",
      "An origination platform is working when the audit question answers itself — any file, any decision, exported in minutes in the format the inspector wants. That's an architectural choice: every state change is logged from day one, and credit policy lives as configuration. We've run this exact system as our own product, so the edge cases already have answers.",
    ],
    metrics: [
      { value: "65%", label: "Faster processing" },
      { value: "0→1", label: "Complete audit trail" },
      { value: "8 wks", label: "To first deploy" },
    ],
    features: [
      { title: "Application & document capture", desc: "Guided forms by loan product with checklists, OCR-ready uploads and completeness tracking." },
      { title: "KYC & bureau integration", desc: "Aadhaar/PAN verification and bureau pulls wired into the flow, with consent logs." },
      { title: "Configurable credit policy", desc: "Rules, scoring weights and deviation matrices as editable configuration — not code changes." },
      { title: "Maker-checker approvals", desc: "Approval chains with delegation, deviation logging and reasons captured on record." },
      { title: "Disbursal & repayment", desc: "Agreement generation, disbursal tracking, schedules and automatic NPA classification." },
      { title: "Audit-ready ledgers", desc: "Every state change logged with user, time and reason — inspection-ready exports." },
    ],
    modules: ["Lead & application intake", "KYC & document vault", "Bureau & verification", "Credit decision engine", "Approval workflows", "Agreements & disbursal", "Repayment schedules", "Collections & NPA views"],
    workflow: [
      { title: "Policy to configuration", desc: "Your credit policy, products and approval matrix mapped into system settings." },
      { title: "Thin slice end to end", desc: "Application → KYC → decision → disbursal live on real files by week three." },
      { title: "Integrations", desc: "Bureau, KYC, SMS and payment partners connected with consent and logging." },
      { title: "Parallel & cutover", desc: "Historical files migrated; new applications cut over with the team trained." },
    ],
    integrations: ["CIBIL / Experian", "Aadhaar & PAN KYC", "Payment gateways", "SMS & WhatsApp", "Tally / accounting", "Document e-sign"],
    faqs: [
      { q: "Can it match our existing credit policy?", a: "Yes — policies become editable configuration (rules, scorecards, deviation matrices) so credit team changes don't need developer cycles." },
      { q: "Is it suitable for RBI-audited NBFCs?", a: "The system is built audit-first: maker-checker controls, immutable logs and exportable trails. Regulatory reporting formats are mapped during scoping." },
      { q: "Which loan products does it support?", a: "Personal, business, LAP, vehicle and consumer-durable flows are all supported as product templates with their own document sets and workflows." },
      { q: "Can it co-lend or work with DSAs?", a: "Yes — DSA portals with lead submission and status transparency, plus co-lending data splits, are common extensions we've built." },
    ],
    bestFor: ["NBFCs", "Lending startups", "Loan aggregators", "Microfinance & co-lending", "Gold & vehicle finance firms"],
    relatedServices: ["custom-software", "blockchain", "cloud-devops"],
    relatedIndustries: ["fintech-lending", "real-estate", "retail-ecommerce"],
    painPoints: [
      { title: "Nine days from application to decision", desc: "Files move by email and Excel; the customer accepts a competitor's offer by day four." },
      { title: "KYC in chat threads", desc: "Aadhaar and PAN images shared on WhatsApp — a privacy incident waiting for a complaint." },
      { title: "Decisions taken from memory", desc: "Credit policy applied inconsistently, with deviations nobody approved on record." },
      { title: "Inspections reconstructed by hand", desc: "A regulator's sample request takes weeks to answer, and the credit team stops lending to do it." },
    ],
    quickFacts: [
      { label: "Typical timeline", value: "8–12 wks", sub: "Application → decision live by week 3" },
      { label: "Team on it", value: "4–6", sub: "Architect, backend, mobile, QA" },
      { label: "Starting investment", value: "₹15 lakh", sub: "Single loan product, bureau + KYC" },
      { label: "First working demo", value: "Week 3", sub: "Real files through the thin slice" },
      { label: "Deployment", value: "Your cloud", sub: "Data in regions you choose" },
    ],
    outcomes: [
      "Application-to-decision time cut by more than half with guided intake and inline KYC",
      "Every decision, deviation and disbursal logged with user, time and reason",
      "Credit-policy changes shipped as configuration the same day",
      "Inspection-ready exports produced in minutes, not weeks",
      "Repayment schedules and NPA classification feeding collections automatically",
    ],
    youProvide: [
      "Your credit policy, product templates and approval matrix as they are practised",
      "Bureau, KYC and payment partner credentials (we integrate them)",
      "Historical files for migration, with a sample for reconciliation",
      "A credit owner and a compliance owner for sign-offs",
    ],
    timeSavings: [
      { task: "Application to decision", before: "9 working days", after: "3 working days" },
      { task: "KYC & bureau pull", before: "Manual, 30 min per file", after: "Inline, 2 min" },
      { task: "Audit export", before: "Weeks of reconstruction", after: "Minutes, inspection-ready" },
      { task: "Credit-policy change", before: "Developer cycle, weeks", after: "Configuration, same day" },
    ],
  },
  {
    slug: "healthcare",
    name: "Healthcare Platforms",
    category: "Clinics & hospitals",
    icon: "heartPulse",
    tagline: "Patient records, appointments and billing — private by design",
    description:
      "Clinic and hospital platforms — appointments, EMR, prescriptions, labs, billing and telemedicine — with access control and audit logs on every record.",
    longDescription: [
      "Healthcare software carries a duty the rest of the industry doesn't: patient data is sensitive by default. We build clinic and hospital systems where access is role-scoped, every record view and edit is logged, and data lives in infrastructure you control — the privacy posture is architectural, not a policy page.",
      "The operational core is the queue: appointments across doctors and locations, walk-ins, token flow, EMR with templates per specialty, prescriptions and print-ready formats, lab and radiology orders with result attachments, and pharmacy/billing with inventory where needed.",
      "Patients feel it in the front door: online booking with reminders, WhatsApp reports and prescription delivery links, telemedicine consults with payment, and a patient app or portal for history, documents and invoices — which also cuts front-desk load measurably.",
      "A clinic running on registers and phone diaries pays in idle chairs and exposed data. A third of appointments do not turn up because nobody reminded them, and the slot could not be refilled. A returning patient's history at another branch is invisible, so the consultation starts from zero. Prescriptions handwritten and re-typed at the pharmacy introduce errors and delays. And patient records in paper files and WhatsApp photos are exactly what a privacy complaint or a DPDP audit finds first — with no log of who looked at what.",
      "Clinical software has to be fast enough to use between patients, or it won't be used at all: a one-handed token queue, an EMR template that captures a consult in under a minute, and a prescription that prints and reaches the pharmacy without re-typing. Privacy is architectural underneath — role-scoped access, audit logs, encryption — not a policy page. We go live with the queue and EMR first.",
    ],
    metrics: [
      { value: "-35%", label: "Fewer no-shows" },
      { value: "100%", label: "Records audit-logged" },
      { value: "1 min", label: "Prescription to print" },
    ],
    features: [
      { title: "Appointments & token flow", desc: "Doctor-wise schedules, walk-ins, tokens and live queue displays across locations." },
      { title: "Specialty EMR", desc: "Templates per specialty with vitals, history, prescriptions and attachments — fast enough to use live in consult." },
      { title: "Labs & radiology", desc: "Order tracking, result uploads and abnormal-flag workflows tied to the patient record." },
      { title: "Pharmacy & billing", desc: "Stock-linked billing, insurance/TPA workflows and GST-compliant invoices." },
      { title: "Telemedicine", desc: "Video consults with payment, notes and e-prescriptions in the same patient timeline." },
      { title: "Privacy architecture", desc: "Role-scoped access, full audit logs on every record, encrypted storage and export controls." },
    ],
    modules: ["Appointments & queue", "EMR & prescriptions", "Lab/radiology orders", "Pharmacy & inventory", "Billing & TPA", "Patient portal/app", "Telemedicine", "Reports & compliance"],
    workflow: [
      { title: "Map the patient journey", desc: "Registration to follow-up across your locations, with every touchpoint and form." },
      { title: "Queue & EMR first", desc: "The daily-use path goes live first — appointments, tokens and consult notes." },
      { title: "Revenue layer", desc: "Labs, pharmacy and billing integrate against the same patient record." },
      { title: "Patient self-serve", desc: "Booking, reports and telemedicine rolled out batch-wise with the front desk." },
    ],
    integrations: ["Payment gateways", "WhatsApp Business", "Lab analysers (HL7)", "SMS gateways", "Video consult SDKs", "Excel import"],
    faqs: [
      { q: "Is patient data private in your system?", a: "By architecture: role-scoped access, audit logs on every view and edit, encryption at rest and export controls. Your data lives on infrastructure you own — we never pool it." },
      { q: "Can it work across multiple branches?", a: "Yes — shared patient records with location-wise scheduling, queues and reporting; doctors can see history from any branch with permission." },
      { q: "Does it print prescriptions in our format?", a: "Yes — prescription templates are configured to your letterhead and format, including drug master with dosages and instructions." },
      { q: "Can it connect to our lab machines?", a: "Where analysers expose standard interfaces we integrate directly; otherwise results upload via a fast worklist screen. Both keep records digital end to end." },
    ],
    bestFor: ["Multi-doctor clinics", "Diagnostic labs", "Dental & eye chains", "Small hospitals", "Telemedicine & second-opinion services"],
    relatedServices: ["custom-software", "mobile-app-development", "managed-it"],
    relatedIndustries: ["healthcare", "retail-ecommerce", "travel-hospitality"],
    painPoints: [
      { title: "A third of patients do not turn up", desc: "No reminder chain, so the chair sits idle and the slot is never refilled." },
      { title: "History stops at the branch door", desc: "A patient seen at another location is a stranger at this one." },
      { title: "Prescriptions re-typed at the pharmacy", desc: "Handwritten scripts introduce errors and delays at the counter." },
      { title: "Records in paper and WhatsApp", desc: "No access control and no log of who viewed what — the first thing a privacy audit finds." },
    ],
    quickFacts: [
      { label: "Typical timeline", value: "8–14 wks", sub: "Queue + EMR live by week 3" },
      { label: "Team on it", value: "4–6", sub: "Architect, backend, mobile, QA" },
      { label: "Starting investment", value: "₹10 lakh", sub: "Multi-doctor clinic, one branch" },
      { label: "First working demo", value: "Week 3", sub: "Live queue with your doctors' schedules" },
      { label: "Privacy", value: "Audit-logged", sub: "Every record view and edit" },
    ],
    outcomes: [
      "No-shows cut by a third with WhatsApp reminders and one-tap reschedule",
      "One patient record across every branch, visible with role-based permission",
      "Prescriptions printed and sent in under a minute from consult templates",
      "Labs, pharmacy and billing tied to the same patient timeline",
      "Role-scoped access and audit logs on every record, deployed on infrastructure you own",
    ],
    youProvide: [
      "Doctor schedules, specialties, consultation and treatment-slot rules",
      "Your prescription letterhead and drug master, plus lab and pharmacy processes",
      "A WhatsApp Business number and payment gateway account",
      "A clinical lead and a front-desk lead for testing and sign-off",
    ],
    timeSavings: [
      { task: "Appointment reminders", before: "Reception calls, hours daily", after: "Automated WhatsApp" },
      { task: "Finding patient history", before: "Paper files, 10 min", after: "One search, any branch" },
      { task: "Prescriptions", before: "Handwritten, re-typed for pharmacy", after: "1 min, printed and sent" },
      { task: "Billing & TPA claims", before: "Manual claim forms", after: "Generated from the record" },
    ],
  },
  {
    slug: "logistics-tracking",
    name: "Logistics & Fleet Tracking",
    category: "Transport & delivery",
    icon: "truck",
    tagline: "Every vehicle, consignment and POD on one dashboard",
    description:
      "Fleet and logistics platforms — live vehicle tracking, dispatch, route management, proof-of-delivery and customer tracking links in one system.",
    longDescription: [
      "Logistics runs on phone calls: where is the truck, has it delivered, why is the customer calling. We replace the calls with one live picture — vehicles on a map from GPS devices or driver apps, consignments tied to trips, and exceptions (stops, detours, delays) surfaced before customers notice.",
      "Dispatch gets a workbench: bookings, vehicle assignment, LRT/challan generation, e-way bill readiness and trip-wise P&L with fuel and toll entries. Drivers get a simple app with trip details, POD capture (photo, signature, OTP) and location reporting that survives patchy networks.",
      "Your customers get what they actually want — a tracking link with live status and proof of delivery, plus automatic exception alerts. Finance gets trip-wise profitability instead of month-end spreadsheet archaeology.",
      "Logistics run by phone call costs an operator on every trip. Twenty status calls a day to the dispatch desk is a dispatcher who is not dispatching. A proof of delivery photographed and emailed days later is a detention or shortage dispute settled by whoever's paperwork looks better — usually not yours. An LR and e-way bill typed for fifteen minutes per consignment is a queue at the loading bay. And without fuel, toll and expense capture per trip, the month-end spreadsheet can say the fleet made money without saying which vehicles or routes lost it.",
      "A fleet platform first has to survive a driver's phone in a dead zone — trip details, navigation and POD capture work offline and sync when signal returns. From there: dispatch generates LR and e-way bill data in minutes, customers get a tracking link instead of a status call, and every trip has a P&L. We put vehicles on the map in week one.",
    ],
    metrics: [
      { value: "98%", label: "On-time dispatch" },
      { value: "-20%", label: "Fleet cost typical" },
      { value: "Live", label: "Customer tracking" },
    ],
    features: [
      { title: "Live fleet tracking", desc: "GPS device or app-based location with stops, idle and route-deviation alerts on one map." },
      { title: "Dispatch workbench", desc: "Bookings, vehicle assignment, LRT/challans and e-way bill data generated per trip." },
      { title: "Driver app", desc: "Trip details, navigation, POD capture and offline-tolerant location reporting." },
      { title: "Proof of delivery", desc: "Photo, signature and OTP PODs attached to the consignment, timestamped and geo-tagged." },
      { title: "Customer tracking links", desc: "Shareable live status pages with automatic delay and delivery notifications." },
      { title: "Trip profitability", desc: "Fuel, toll, mileage and expense capture rolled into per-trip and per-vehicle P&L." },
    ],
    modules: ["Booking & consignment", "Fleet & vehicle master", "Dispatch & trips", "Driver app & POD", "Live tracking map", "Customer notifications", "LRT/challan & e-way", "Profitability reports"],
    workflow: [
      { title: "Model your network", desc: "Routes, vehicle types, rate structures and POD rules mapped in scoping." },
      { title: "Tracking first", desc: "Vehicles live on the map in week one — the visibility win lands immediately." },
      { title: "Dispatch & documents", desc: "Trips, LRT/challans and driver app rolled out depot by depot." },
      { title: "Customer layer", desc: "Tracking links and exception alerts switched on once data quality is proven." },
    ],
    integrations: ["GPS device APIs", "FASTag data", "Payment gateways", "SMS & WhatsApp", "Tally", "Fuel card feeds"],
    faqs: [
      { q: "Do we need GPS devices in every vehicle?", a: "No — the driver app reports location on its own. GPS devices add precision and work when phones don't; we support both and often mixed fleets." },
      { q: "Can customers self-track their consignment?", a: "Yes — a shareable link shows live status and delivery proof, with automatic alerts on exceptions. It usually cuts 'where is my load' calls dramatically." },
      { q: "Does it handle part-load and full-truck differently?", a: "Yes — LTL bookings consolidate onto trips with weight-wise rates; FTL runs as dedicated trips. Both feed the same profitability reporting." },
      { q: "What about offline areas?", a: "The driver app caches trips and PODs offline and syncs when signal returns; the map simply shows last-known positions with timestamps." },
    ],
    bestFor: ["Fleet operators", "Courier & last-mile", "Bulk & breakbulk movers", "Cold-chain operators", "E-commerce fulfilment teams"],
    relatedServices: ["custom-software", "mobile-app-development", "cloud-devops"],
    relatedIndustries: ["logistics", "retail-ecommerce", "manufacturing"],
    painPoints: [
      { title: "The dispatch desk is a call centre", desc: "Twenty 'where is my load' calls a day from customers who have no tracking link." },
      { title: "Disputes settled by paperwork", desc: "Photographed trip sheets emailed days later lose detention and shortage arguments." },
      { title: "Documents typed at the loading bay", desc: "Fifteen minutes per LR and e-way bill, with a queue of trucks waiting." },
      { title: "Profit known per month, not per trip", desc: "Fuel, toll and expenses reconciled at month-end, so losing routes are invisible." },
    ],
    quickFacts: [
      { label: "Typical timeline", value: "8–14 wks", sub: "Vehicles on the map by week 1" },
      { label: "Team on it", value: "4–5", sub: "Architect, backend, mobile, QA" },
      { label: "Starting investment", value: "₹10 lakh", sub: "Dispatch, driver app, tracking links" },
      { label: "First working demo", value: "Week 3", sub: "Live trips with proof of delivery" },
      { label: "Offline", value: "First", sub: "Driver app survives dead zones" },
    ],
    outcomes: [
      "Every vehicle live on one map with stop, idle and route-deviation alerts",
      "Geo-tagged photo, signature or OTP proof of delivery on every consignment",
      "LR and e-way bill data generated per trip in minutes",
      "Customer tracking links that remove most status calls to the desk",
      "Trip-wise and vehicle-wise profitability from captured fuel, toll and expenses",
    ],
    youProvide: [
      "Your vehicle master, routes, rate structures and POD rules",
      "Driver phones for testing, and any GPS or reefer devices already fitted",
      "Your LR and e-way bill formats and customer notification preferences",
      "A dispatch owner and a finance owner for sign-offs",
    ],
    timeSavings: [
      { task: "Trip status calls", before: "20+ a day to the ops desk", after: "Customer tracking link" },
      { task: "Proof-of-delivery collection", before: "Photographed and emailed, days later", after: "Instant, geo-tagged" },
      { task: "LR / e-way bill preparation", before: "15 min per consignment", after: "2 min, pre-filled" },
      { task: "Trip profitability", before: "Month-end spreadsheet", after: "Per trip, live" },
    ],
  },
  {
    slug: "real-estate-crm",
    name: "Real Estate CRM",
    category: "Property sales",
    icon: "building",
    tagline: "Enquiry to registration in one accountable pipeline",
    description:
      "Real-estate CRMs with lead scoring, broker management, site-visit scheduling and document workflows — from first enquiry to registration.",
    longDescription: [
      "Real-estate sales lose money in the gaps: broker leads that never get called, site visits without follow-up, and documents moving on WhatsApp between sales, CRM and legal. We build the CRM that closes those gaps — one pipeline from enquiry to registration, with every lead owned and every next action scheduled.",
      "Lead management is source-aware: portal feeds, websites, walk-ins and broker networks land in one system with automated scoring by budget, location and engagement. Sales follow structured cadences; managers see source-wise conversion and can kill what doesn't work.",
      "Site visits get operational: scheduling with reminders, mobile check-in on arrival, and visit-to-booking conversion per project. The document workflow carries the deal home — agreements, payment schedules, registration status — so sales and legal work off one record instead of a WhatsApp thread.",
      "Property sales without a system lose money in the gaps between people. Four enquiries in ten are never contacted a second time because nobody owned them — and each one cost real money to generate on a portal or a hoarding. Site visits booked over the phone are forgotten, so the buyer who did turn up meets nobody. Broker commissions reconciled monthly from memory produce disputes that sour the channel. And agreements, demand letters and registration status moving between sales and legal on WhatsApp mean closures slip by weeks and RERA disclosures are a scramble.",
      "The rule that lifts conversion: no lead exists without a next action and a due date. Portal and broker leads arrive scored, site visits are booked and checked in on a phone, missed actions escalate the same day, and a booked unit's payments and documents live on one record. We build the pipeline first, live on real leads by week three.",
    ],
    metrics: [
      { value: "2.1×", label: "More site visits" },
      { value: "30%", label: "Faster closure" },
      { value: "0", label: "Leads unowned" },
    ],
    features: [
      { title: "Every source, one pipeline", desc: "Portals, website, walk-ins and brokers consolidated with source tagging and duplicate detection." },
      { title: "Lead scoring & routing", desc: "Budget, location and engagement scored; auto-assigned by project and round-robin rules." },
      { title: "Site-visit scheduling", desc: "Reminders to buyers, mobile check-in by sales, and conversion tracking per project and tower." },
      { title: "Broker & channel partners", desc: "Partner portals with lead submission, status visibility and commission tracking." },
      { title: "Payment milestones", desc: "Demand letters, receipts and outstanding tracking aligned to construction-linked plans." },
      { title: "Document workflows", desc: "Agreement and registration status tracked on the unit record — legal and sales in sync." },
    ],
    modules: ["Lead capture & scoring", "Sales pipeline", "Site visits & check-in", "Broker portal", "Unit inventory & pricing", "Payment milestones", "Documents & registration", "Channel analytics"],
    workflow: [
      { title: "Map the journey", desc: "Sources, stages, teams and per-project pricing structures documented first." },
      { title: "Pipeline live", desc: "Lead capture, scoring and cadences live on real leads within weeks." },
      { title: "Visits & brokers", desc: "Scheduling, check-in and partner portal rolled out to the field team." },
      { title: "Revenue workflows", desc: "Milestones and documents connected; management dashboards completed." },
    ],
    integrations: ["99acres / MagicBricks feeds", "WhatsApp Business", "Payment gateways", "SMS gateways", "Tally", "Email"],
    faqs: [
      { q: "Does it pull leads from property portals automatically?", a: "Yes — portal leads flow in via API or email parsing, deduplicated and scored. Your team works one list, not six dashboards." },
      { q: "Can brokers see their own leads' status?", a: "Yes — a partner portal shows submission status and site-visit outcomes, which keeps channel partners engaged and honest." },
      { q: "Does it handle construction-linked payment plans?", a: "Yes — demand generation, receipts and outstanding reports track per unit against the milestone plan, with Tally sync." },
      { q: "How does it stop leads being missed?", a: "Every lead has a mandatory next action with a due date; missed actions escalate to the manager. That single rule is what lifts conversion." },
    ],
    bestFor: ["Developers & builders", "Brokerage firms", "Channel-sales teams", "Commercial leasing", "Plot & township marketers"],
    relatedServices: ["custom-software", "web-development", "digital-marketing"],
    relatedIndustries: ["real-estate", "construction", "professional-services"],
    painPoints: [
      { title: "Four in ten enquiries never called twice", desc: "Portal, hoarding and broker leads land in different inboxes with no owner." },
      { title: "Site visits booked and forgotten", desc: "Buyers who turn up meet nobody; conversion per project is unknown." },
      { title: "Broker commissions disputed monthly", desc: "Reconciled from memory and WhatsApp, souring the channel that brings the leads." },
      { title: "Documents on WhatsApp", desc: "Agreements, demand letters and registration status move between sales and legal by chat." },
    ],
    quickFacts: [
      { label: "Typical timeline", value: "6–12 wks", sub: "Pipeline live by week 3" },
      { label: "Team on it", value: "3–5", sub: "Architect, backend, front-end, QA" },
      { label: "Starting investment", value: "₹8 lakh", sub: "Single project with broker portal" },
      { label: "First working demo", value: "Week 3", sub: "Your real leads, scored and owned" },
      { label: "Portal feeds", value: "Automatic", sub: "99acres, MagicBricks and more" },
    ],
    outcomes: [
      "Every lead from every source in one pipeline with a mandatory next action",
      "Site visits scheduled, reminded and checked in — with conversion per project",
      "Broker portal with lead status and auto-computed commissions",
      "Unit inventory, milestone payments and demand letters on one record",
      "Agreement and registration status shared between sales and legal, not chat",
    ],
    youProvide: [
      "Portal account access and your broker network list",
      "Project, tower and unit inventory with pricing and payment plans",
      "Your agreement templates and RERA disclosure requirements",
      "A sales head and a legal owner for the weekly demo",
    ],
    timeSavings: [
      { task: "Lead follow-up", before: "40% never called a second time", after: "Mandatory next action on every lead" },
      { task: "Site-visit scheduling", before: "Phone and memory", after: "Booked, reminded, checked in" },
      { task: "Broker commission reconciliation", before: "Monthly disputes", after: "Portal, auto-computed" },
      { task: "Demand letters", before: "Typed per unit", after: "Generated per milestone" },
    ],
  },
  {
    slug: "food-delivery",
    name: "Food Delivery & Restaurants",
    category: "Food & beverage",
    icon: "utensils",
    tagline: "Your own ordering channel — not just another commission",
    description:
      "Restaurant ordering and delivery platforms — your own app and web store, kitchen display, rider management and menu control, without aggregator commissions.",
    longDescription: [
      "Aggregators take 25–30% of every order and own the customer relationship. A direct channel doesn't replace them, but every order that moves to it is margin and data you keep. We build restaurants their own ordering apps and web stores — branded, fast, and tuned for the neighbourhood regular who orders weekly.",
      "The ordering flow is engineered for conversion: menu with photos and variants, one-tap repeat of last order, UPI-first checkout, live order tracking and WhatsApp updates. Loyalty keeps regulars returning — stamps, wallets and birthday offers that aggregators will never run for you.",
      "Inside, operations run on a kitchen display system instead of paper KOTs: order queue with prep times, rider assignment with live tracking for own-fleet deliveries, and a manager view of sales, discounts and item-level profitability that reconciles with your POS.",
      "Depending entirely on aggregators is a cost that compounds with every order. A 28–30% commission on the majority of delivery revenue is the single largest line after ingredients. Phone orders taken by shouting to the kitchen have no payment capture, no history and no way to reorder. Loyalty on paper stamp cards is loyalty nobody redeems. And because the aggregator owns the customer relationship, a regular who orders every week is someone you have never met — and someone the platform can steer to a competitor tomorrow.",
      "A direct channel only wins if ordering from you is faster than opening the aggregator app: no install, a menu that loads instantly, UPI in one tap, and the order landing on the same kitchen printer as an aggregator order. We launch to your existing regulars first — with QR cards and bag inserts — then add loyalty once order data shows what works.",
    ],
    metrics: [
      { value: "0%", label: "Commission on direct" },
      { value: "1 tap", label: "Repeat last order" },
      { value: "Live", label: "Kitchen display" },
    ],
    features: [
      { title: "Branded ordering apps", desc: "Your app and web store with your menu, photos and offers — customers belong to you." },
      { title: "UPI-first checkout", desc: "Fast payments with saved addresses and one-tap repeat ordering for regulars." },
      { title: "Kitchen display system", desc: "Live order queue with prep timers replacing paper KOTs — fewer errors, faster service." },
      { title: "Own-fleet delivery", desc: "Rider app with order batching, live tracking and proof-of-delivery for your delivery team." },
      { title: "Loyalty & offers", desc: "Stamps, wallets, coupon rules and birthday offers aggregators can't run on your behalf." },
      { title: "Item-level analytics", desc: "Sales, discounts and margin per item — with POS reconciliation for the full picture." },
    ],
    modules: ["Menu & catalogue", "Ordering app & web store", "Payments & checkout", "Kitchen display system", "Rider app & tracking", "Loyalty & coupons", "Manager analytics", "POS reconciliation"],
    workflow: [
      { title: "Menu & brand setup", desc: "Catalogue, photos, variants, taxes and delivery zones configured with you." },
      { title: "Ordering live", desc: "App and web store launched to your existing regulars first — fastest adoption." },
      { title: "Kitchen & delivery", desc: "KDS and rider app rolled in; aggregator orders can flow into the same KDS." },
      { title: "Loyalty & tune", desc: "Retention programmes switched on once order data shows the patterns." },
    ],
    integrations: ["Razorpay / Cashfree", "WhatsApp Business", "Existing POS / KOT", "SMS gateways", "Google Maps", "GST invoicing"],
    faqs: [
      { q: "Can it run alongside Swiggy and Zomato?", a: "Yes — aggregator orders can feed into the same kitchen display while direct orders stay commission-free. Most clients grow the direct share steadily." },
      { q: "Do we need our own delivery riders?", a: "Either model works — own-fleet with the rider app, or pickup/dine-in focus without delivery. Hyperlocal third-party delivery can also be integrated." },
      { q: "How do customers find the direct channel?", a: "Insert cards, WhatsApp broadcasts, table QR codes and loyalty incentives — we've seen regulars shift within weeks when the repeat-order experience is one tap." },
      { q: "What does it cost to run?", a: "A fixed build cost and modest hosting — no per-order commission. Most restaurants recover the build from direct-order margin within the first year." },
    ],
    bestFor: ["Restaurants & QSRs", "Cloud kitchens", "Bakeries & cafés", "Tiffin & meal services", "Dark stores & grocery delivery"],
    relatedServices: ["mobile-app-development", "web-development", "digital-marketing"],
    relatedIndustries: ["retail-ecommerce", "travel-hospitality", "logistics"],
    painPoints: [
      { title: "A third of every order goes to the aggregator", desc: "Commission is the largest cost after ingredients, on the majority of delivery revenue." },
      { title: "Phone orders reach the kitchen by shouting", desc: "No payment capture, no history, no reorder — and errors at the pass." },
      { title: "Loyalty on stamp cards", desc: "Paper schemes nobody carries and nobody redeems." },
      { title: "You have never met your regulars", desc: "The platform owns the relationship and can steer the customer elsewhere tomorrow." },
    ],
    quickFacts: [
      { label: "Typical timeline", value: "6–12 wks", sub: "Ordering live by week 3, outlets after" },
      { label: "Team on it", value: "3–5", sub: "Architect, front-end, backend, QA" },
      { label: "Starting investment", value: "₹5 lakh", sub: "Single outlet with KDS integration" },
      { label: "First working demo", value: "Week 3", sub: "Your menu, real orders to the kitchen" },
      { label: "Commission on direct", value: "0%", sub: "Build cost, then hosting only" },
    ],
    outcomes: [
      "A branded ordering app and web store with one-tap repeat orders from WhatsApp",
      "Direct orders printed straight to the kitchen through your existing POS",
      "UPI-first checkout with live tracking and WhatsApp updates",
      "A loyalty programme redeemable across outlets, with measurable repeat rates",
      "Direct share, item-level margin and aggregator reconciliation on one dashboard",
    ],
    youProvide: [
      "Your menu with variants, photos, taxes and delivery zones",
      "Details of the existing POS and kitchen printers at each outlet",
      "A payment gateway and WhatsApp Business account (we help set up)",
      "An outlet manager to pilot the first location",
    ],
    timeSavings: [
      { task: "Order entry to kitchen", before: "Phone, shout, paper KOT", after: "Direct to the kitchen printer" },
      { task: "Repeat orders", before: "Full re-entry every time", after: "Two taps on WhatsApp" },
      { task: "Aggregator commission", before: "28–30% per order", after: "0% on direct orders" },
      { task: "Item-level margin", before: "Unknown until month-end", after: "Live per outlet" },
    ],
  },
];