import { launch, newPage, go, sleep, text, check, summary } from "./scripts/qa/lib.mjs";
const b = await launch();
const p = await newPage(b, { width: 1280, height: 900 });
await go(p, "/careers");
const role = await p.$eval("#open-roles article h3", (e) => e.textContent.trim());
// click on the card's summary text (not the title) — the whole card should open the job
await p.$eval("#open-roles", (e) => e.scrollIntoView());
await sleep(1500);
const box = await (await p.$("#open-roles article p")).boundingBox();
await p.mouse.click(box.x + 20, box.y + 5);
await p.waitForFunction(() => /\/careers\/[a-z0-9-]+$/.test(location.pathname), { timeout: 30000 }).catch(() => {});
await sleep(1500);
check("clicking the card opens the job page", /\/careers\/[a-z0-9-]+$/.test(p.url()), p.url());
const t = await text(p);
check("title shown", t.includes(role));
for (const s of ["About the role", "What you'll do", "What we're looking for", "What you get", "Job overview", "Location", "Employment type", "Other open roles"]) check(`section: ${s}`, t.includes(s));
check("job-posting data present", (await p.$$eval('script[type="application/ld+json"]', (s) => s.map((x) => x.textContent).join(""))).includes('"JobPosting"'));
await p.screenshot({ path: ".shots/career-detail.png" });
await p.$$eval("aside button", (bs) => bs[0].click());
await p.waitForSelector("#apply-position", { timeout: 10000 });
check("Apply on the job page prefills the role", (await p.$eval("#apply-position", (e) => e.value)) === role);
await p.keyboard.press("Escape");
await go(p, "/careers");
await p.$$eval("#open-roles article button", (bs) => bs[0].click());
await sleep(500);
check("Apply on the card still opens the popup (no navigation)", p.url().endsWith("/careers") && !!(await p.$("#apply-name")));
const r = await fetch("http://localhost:3100/careers/no-such-role");
check("unknown role → 404", r.status === 404);
const sm = await (await fetch("http://localhost:3100/sitemap.xml")).text();
check("job pages in sitemap", /\/careers\/[a-z0-9-]+</.test(sm));
check("no browser errors", p.problems.length === 0, p.problems.join(" | "));
await b.close();
summary();
